name: Create Tag

on:
  push:
    branches:
      - main
jobs:
  build:
    if: |
      github.event.pusher.name == github.event.repository.owner.name
       && startsWith(github.event.head_commit.message, 'Release')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tag
      id: tagger-action
      uses: christophebedard/tag-version-commit@v1
      with:
        token: ${{ secrets.GB_TOKEN }}
        version_regex: 'Release v?([0-9]+\.[0-9]+\.[0-9]+)'
        version_tag_prefix: 'v'
        check_entire_commit_message: true
        version_assertion_command: 'grep -q "\"version\": \"$version\"" package.json'
    - name: Tag Empty output
      if: ${{ steps.tagger-action.outputs.tag == '' }}
      run: echo 'The not created.'
    - name: Tag Created output
      if: ${{ steps.tagger-action.outputs.tag != '' }}
      run: echo "Tag created ${{ steps.tagger-action.outputs.tag }}"
