name: Build

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - run: npm run build:production
      - uses: EndBug/add-and-commit@v7
        with:
          committer_name: GitHub Actions
          message: 'Automatic build by github action'
          add: 'dist'
