name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dist:
              - 'dist/**'
            js:
              - 'src/js/**'
      - name: Checking PR
        if: steps.changes.outputs.dist == 'true'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Automated message. Please read the [CONTRIBUTING](./CONTRIBUTING.md) before doing a PR. Dist files should not be included, the files are generated automatically on merge.'
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
      - if: steps.changes.outputs.dist == 'true'
        run: exit 1
      - name: Check if Javascript lint is required
        if: success() && steps.changes.outputs.js == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        if: steps.changes.outputs.js == 'true'
        run: npm ci
      - name: Run eslint
        if: steps.changes.outputs.js == 'true'
        uses: sibiraj-s/action-eslint@v2
        with:
          eslint-args: '-c .eslintrc.json --ignore-path=.gitignore --max-warnings=0 --quiet'
          extensions: "ts,tsx,js,jsx"
