name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        run: yarn
      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v7.3
        with:
          config_path: ".eslintrc.json"
          ignore_path: ".gitignore"
          extensions: "ts,tsx,js,jsx"
          extra_args: "--max-warnings=0"

  build:
    needs: eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - run: npm run build:production
      - uses: EndBug/add-and-commit@v7
        with:
          committer_name: GitHub Actions
          message: 'Automatic build by github action'
          add: 'dist'
