name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        run: yarn
      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v7.3
        with:
          config_path: ".eslintrc.json"
          ignore_path: ".gitignore"
          extensions: "ts,tsx,js,jsx"
          extra_args: "--max-warnings=0"
