name: Lint

on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dist:
              - 'dist/**'

      - name: Check for dist files
        if: steps.changes.outputs.dist == 'true'
        uses: andymckay/cancel-action@0.2
      - name: Hulk
        run: echo 'Doing hulk.'

  eslint:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            js:
              - 'src/js/**'

      - uses: actions/setup-node@v2
        if: steps.changes.outputs.js == 'true'
        with:
          node-version: 14
      - name: Install
        if: steps.changes.outputs.js == 'true'
        run: yarn
      - name: Run eslint
        if: steps.changes.outputs.js == 'true'
        uses: tj-actions/eslint-changed-files@v7.3
        with:
          config_path: ".eslintrc.json"
          ignore_path: ".gitignore"
          extensions: "ts,tsx,js,jsx"
          extra_args: "--max-warnings=0"
