name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dist:
              - 'dist/**'
            js:
              - 'src/js/**'
      - name: Checking PR
        if: steps.changes.outputs.dist == 'true'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Automated message. Please read the [CONTRIBUTING](./CONTRIBUTING.md) before doing a PR. Dist files should not be included, the files are generated automatically on merge.'
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
      - if: steps.changes.outputs.dist == 'true'
        run: exit 1
      - name: Run eslint
        if: steps.changes.outputs.js == 'true'
        run: |
          npm ci
          npm run test
